### PR TITLE
Removed not_in_cluster fix

### LINKED ISSUE #191: Remove `not_in_cluster`
Agent should not collect not_in_cluster VMs, just throw them away.

### PR DESCRIPTION
**Pull request by amreo**
Fix #191

### CODE REVIEW

File: fetch/linux/oratab.sh [hunk 1]
```diff
@@ -24,7 +24,7 @@ fi
 
 if [ ! -r "$ORATAB" ]; then
   >&2 echo "The file $ORATAB doesn't exist or isn't readable"
-  exit 1
+  exit 0
```
Comment (cirelli94) [inline fetch/linux/oratab.sh:27]: Why? Exit code should be 0 if there are no error, but this is an error.

Comment (amreo) [reply fetch/linux/oratab.sh:27]: Do you not have opened a issue that say ercole-agent should not fail if oratab is not readable (#133) ?

Comment (cirelli94) [reply fetch/linux/oratab.sh:27]: Not exactly: it should execute successfully without any db installed, not if the oratab is not readable.
In fact, it was possible now disabling OracleDatabase feature in config.json.
This functionality was added later and that issue could already be closed. Amen.
